"""Application defaults kept in one place for easy Raspberry Pi tuning."""

APP_TITLE = "Dynamic TV Backlight Tracker"
DEFAULT_CAMERA_INDEX = 0
DEFAULT_FRAME_WIDTH = 1280
DEFAULT_FRAME_HEIGHT = 720
DEFAULT_CAMERA_FPS = 30
DEFAULT_BORDER_WIDTH = 24
DEFAULT_SAMPLE_STEP = 2
DEFAULT_SMOOTHING = 0.25
DEFAULT_REFRESH_SECONDS = 0.08
MIN_ROI_SIZE = 8
